Repository c15t/c15t, pull requests merged in 2025-02, with the labels that each got.

#51 fix(elements): Centered thumb & fixed disabled state
  packages/elements/src/react/ui/components/switch.css
  packages/elements/src/react/ui/components/switch.tsx
Labels: 🐛 bug

#52 fix(elements): centered customize consent dialog
  packages/elements/src/react/consent-manager-dialog/consent-manager-dialog.css
Labels: 🐛 bug, 🤝🏻 help-welcome, ✅ good-first-issue

#54 feat(core): prevent changes to disabled consent types
  packages/core/src/store.ts
Labels: ✨ feature, ✅ good-first-issue

#55 docs: add cursor rules for specific packages
  .cursor/rules/docs-rules.mdc
  .cursor/rules/elements-rules.mdc
  .cursor/rules/global-rules.mdc
Labels: 📚 docs, 🤝🏻 help-welcome, 💭 discussion, ✅ good-first-issue

#67 feat(core): added automatic script blocking
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/libs/__tests__/tracking-blocker.test.ts
  packages/core/src/libs/tracking-blocker.ts
  packages/core/src/libs/tracking-domains.ts
  packages/core/src/store.ts
  packages/core/vitest.config.ts
  packages/react/src/common/components/consent-manager-provider.tsx
  packages/react/src/common/types/consent-manager.ts
  pnpm-lock.yaml
Labels: ✨ feature, ✅ good-first-issue

#72 fix(react): sandpack dialog footer not using dark theme
  packages/react/src/consent-manager-widget/consent-manager-widget.css
Labels: 🐛 bug

#77 fix(react,core): improve consent button and store behavior
  packages/core/src/store.ts
  packages/react/src/consent-manager-widget/atoms/button.tsx
  packages/react/src/consent-manager-widget/atoms/footer.tsx
  packages/react/src/primitives/button.tsx
Labels: 🐛 bug

#74 fix(react): fixed button can't be decendant error
  apps/docs/src/content/framework/react/consent-manager-dialog.mdx
  apps/docs/src/content/framework/react/consent-manager-widget.mdx
  apps/docs/src/content/framework/react/guides/customization.mdx
  packages/react/src/consent-manager-dialog/atoms/dialog-card.tsx
  packages/react/src/consent-manager-widget/__tests__/styles.spec.tsx
  packages/react/src/consent-manager-widget/atoms/accordion.tsx
  packages/react/src/consent-manager-widget/atoms/logo.tsx
  packages/react/src/consent-manager-widget/consent-manager-widget.css
  packages/react/src/consent-manager-widget/consent-manager-widget.tsx
  packages/react/src/consent-manager-widget/index.ts
  packages/react/src/consent-manager-widget/theme.ts
  packages/react/src/ui/components/accordion.css
  packages/react/src/ui/components/accordion.tsx
  packages/react/src/ui/components/logo.tsx
Labels: 🐛 bug, 🤝🏻 help-welcome, ✅ good-first-issue

#82 fix(react): Improve dialog mobile friendliness
  packages/react/src/consent-manager-dialog/consent-manager-dialog.css
  packages/react/src/consent-manager-widget/consent-manager-widget.css
  packages/react/src/cookie-banner/cookie-banner.css
Labels: 🐛 bug

#81 feat(core,react): add noStyle option to ConsentManagerProvider
  packages/core/src/store.initial-state.ts
  packages/core/src/store.ts
  packages/core/src/store.type.ts
  packages/react/src/common/components/consent-manager-provider.tsx
  packages/react/src/common/utils/theme.ts
Labels: 🐛 bug, 🎨 ui, 🤝🏻 help-welcome, ✅ good-first-issue

#79 fix(core,react): hide cookie banner when customizing consent
  packages/core/src/store.type.ts
  packages/react/src/primitives/button.tsx
Labels: 🐛 bug

#87 docs(core,react): Add API reference documentation
  apps/docs/src/content/core/api-reference.mdx
  apps/docs/src/content/framework/react/api-reference.mdx
  apps/docs/src/content/framework/react/meta.json
Labels: 📚 docs

#96 docs(core,react): Added example pages, added tailwind + css examples
  apps/docs/src/app/(home)/_components/examples.tsx
  apps/docs/src/content/core/examples/javascript.mdx
  apps/docs/src/content/core/meta.json
  apps/docs/src/content/framework/react/consent-manager-dialog.mdx
  apps/docs/src/content/framework/react/consent-manager-widget.mdx
  apps/docs/src/content/framework/react/cookie-banner.mdx
  apps/docs/src/content/framework/react/examples/css-variables.mdx
  apps/docs/src/content/framework/react/examples/css.mdx
  apps/docs/src/content/framework/react/examples/tailwind.mdx
  apps/docs/src/content/framework/react/index.mdx
  apps/docs/src/content/framework/react/meta.json
  apps/docs/src/content/framework/react/use-consent-manager.mdx
  apps/docs/src/examples/react/cookie-banner/example-page.tsx
  apps/docs/src/examples/react/cookie-banner/index.tsx
  apps/docs/src/examples/react/css-variables/example-page.tsx
  apps/docs/src/examples/react/css-variables/index.tsx
  apps/docs/src/examples/react/css/example-page.tsx
  apps/docs/src/examples/react/css/index.tsx
  apps/docs/src/examples/react/dialog/example-page.tsx
  apps/docs/src/examples/react/dialog/index.tsx
  apps/docs/src/examples/react/tailwind/example-page.tsx
  apps/docs/src/examples/react/tailwind/index.tsx
  apps/docs/src/examples/react/use-consent-manager/example.tsx
  apps/docs/src/examples/react/use-consent-manager/index.tsx
  apps/docs/src/examples/react/widget/example-page.tsx
  apps/docs/src/examples/react/widget/index.tsx
  packages/react/src/consent-manager-widget/atoms/button.tsx
  packages/react/src/consent-manager-widget/atoms/footer.tsx
  packages/react/src/consent-manager-widget/consent-manager-widget.tsx
  packages/react/src/consent-manager-widget/index.ts
Labels: 📚 docs

#101 chore: :construction: renamed koroflow to c15t
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  README.md
  apps/docs/next.config.mjs
  apps/docs/public/logo-dark-mode.png
  apps/docs/public/logo-icon.png
  apps/docs/public/logo-icon@2x.png
  apps/docs/public/logo-light-mode.png
  apps/docs/public/logo.svg
  apps/docs/public/logomark.svg
  apps/docs/src/app/(home)/config.tsx
  apps/docs/src/app/docs/[[...slug]]/page.tsx
  apps/docs/src/app/layout.config.tsx
  apps/docs/src/components/docs/installer.tsx
  apps/docs/src/components/docs/powered-by.tsx
  apps/docs/src/components/docs/search.tsx
  apps/docs/src/components/logo.tsx
  apps/docs/src/content/framework/react/guides/translation.mdx
  apps/docs/src/content/getting-started/index.mdx
  apps/docs/src/content/getting-started/open-source/contributing.mdx
  packages/core/README.md
  packages/dev-tools/README.md
  packages/react/README.md
Labels: ✨ feature, 📚 docs
